CREATE TABLE `seoPages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`url` varchar(500) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`pageType` enum('homepage','city','state_law','company','blog','service','report','other') NOT NULL,
	`title` varchar(255),
	`metaDescription` text,
	`hasCanonical` int NOT NULL DEFAULT 0,
	`hasSchema` int NOT NULL DEFAULT 0,
	`schemaTypes` varchar(500),
	`inSitemap` int NOT NULL DEFAULT 0,
	`inImageSitemap` int NOT NULL DEFAULT 0,
	`hasInternalLinksOut` int NOT NULL DEFAULT 0,
	`hasInternalLinksIn` int NOT NULL DEFAULT 0,
	`gscIndexStatus` enum('indexed','not_indexed','excluded','unknown') NOT NULL DEFAULT 'unknown',
	`gscClicks` int DEFAULT 0,
	`gscImpressions` int DEFAULT 0,
	`gscAvgPosition` varchar(10),
	`gscLastChecked` timestamp,
	`canonicalUrl` varchar(500),
	`isDuplicate` int NOT NULL DEFAULT 0,
	`duplicateOf` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seoPages_id` PRIMARY KEY(`id`),
	CONSTRAINT `seoPages_url_unique` UNIQUE(`url`)
);
--> statement-breakpoint
CREATE TABLE `seoStrategy` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category` enum('technical_seo','content','schema','link_building','indexing','analytics','tooling') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`implementation` text,
	`result` text,
	`duplicationNotes` text,
	`status` enum('planned','in_progress','completed','skipped') NOT NULL DEFAULT 'planned',
	`impact` enum('high','medium','low') NOT NULL DEFAULT 'medium',
	`pagesAffected` int DEFAULT 0,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seoStrategy_id` PRIMARY KEY(`id`)
);
