CREATE TABLE `backlinkOpportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200),
	`url` varchar(500) NOT NULL,
	`type` enum('press_release','directory','guest_post','resource_page','forum','social','other') NOT NULL,
	`discoveredVia` varchar(200),
	`relevanceScore` int,
	`relevanceReason` text,
	`domainAuthority` int,
	`doFollow` int DEFAULT 1,
	`status` enum('new','approved','rejected','promoted') NOT NULL DEFAULT 'new',
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `backlinkOpportunities_id` PRIMARY KEY(`id`),
	CONSTRAINT `backlinkOpportunities_url_unique` UNIQUE(`url`)
);
--> statement-breakpoint
CREATE TABLE `backlinkTargets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`url` varchar(500) NOT NULL,
	`submitUrl` varchar(500),
	`type` enum('press_release','directory','guest_post','resource_page','forum','social','other') NOT NULL,
	`domainAuthority` int,
	`domainRating` int,
	`estimatedTraffic` int,
	`doFollow` int NOT NULL DEFAULT 1,
	`requiresAccount` int DEFAULT 0,
	`requiresPayment` int DEFAULT 0,
	`submissionMethod` enum('http_api','playwright','manual') NOT NULL DEFAULT 'playwright',
	`accountEmail` varchar(320),
	`accountPassword` varchar(500),
	`accountUsername` varchar(200),
	`accountNotes` text,
	`lastSubmittedAt` timestamp,
	`lastPublishedUrl` varchar(1000),
	`totalSubmissions` int NOT NULL DEFAULT 0,
	`successfulSubmissions` int NOT NULL DEFAULT 0,
	`status` enum('active','inactive','banned') NOT NULL DEFAULT 'active',
	`notes` text,
	`priority` int NOT NULL DEFAULT 50,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `backlinkTargets_id` PRIMARY KEY(`id`),
	CONSTRAINT `backlinkTargets_url_unique` UNIQUE(`url`)
);
