CREATE TABLE `lawFirms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`contactName` varchar(200),
	`email` varchar(320),
	`phone` varchar(30),
	`website` varchar(500),
	`coveredStates` text,
	`coveredCities` text,
	`exclusiveStates` text,
	`pricePerLead` decimal(8,2) NOT NULL DEFAULT '0',
	`billingCycle` enum('per_lead','weekly','monthly') NOT NULL DEFAULT 'per_lead',
	`webhookUrl` varchar(1000),
	`webhookSecret` varchar(255),
	`emailDelivery` int NOT NULL DEFAULT 1,
	`minLeadScore` int DEFAULT 0,
	`filterCompanies` text,
	`filterProblemTypes` text,
	`maxLeadsPerDay` int,
	`maxLeadsPerMonth` int,
	`status` enum('active','paused','inactive') NOT NULL DEFAULT 'active',
	`notes` text,
	`totalLeadsDelivered` int NOT NULL DEFAULT 0,
	`totalLeadsAccepted` int NOT NULL DEFAULT 0,
	`totalLeadsRejected` int NOT NULL DEFAULT 0,
	`totalRevenue` decimal(10,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lawFirms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leadDeliveries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`firmId` int NOT NULL,
	`leadScore` int NOT NULL DEFAULT 0,
	`scoreBreakdown` text,
	`deliveryMethod` enum('webhook','email','manual') NOT NULL DEFAULT 'webhook',
	`webhookStatusCode` int,
	`webhookResponse` text,
	`deliveredAt` timestamp,
	`accepted` enum('pending','accepted','rejected','duplicate') NOT NULL DEFAULT 'pending',
	`rejectionReason` varchar(500),
	`acceptedAt` timestamp,
	`charged` int NOT NULL DEFAULT 0,
	`chargeAmount` decimal(8,2),
	`chargedAt` timestamp,
	`invoiceRef` varchar(200),
	`status` enum('pending','delivered','failed','retrying') NOT NULL DEFAULT 'pending',
	`retryCount` int NOT NULL DEFAULT 0,
	`lastError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leadDeliveries_id` PRIMARY KEY(`id`)
);
