CREATE TABLE `agentActions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentSlug` varchar(50) NOT NULL,
	`priority` enum('p1','p2','p3','p4','p5') NOT NULL DEFAULT 'p3',
	`title` varchar(500) NOT NULL,
	`description` text,
	`actionType` varchar(100) NOT NULL,
	`payload` text,
	`status` enum('queued','running','completed','failed','blocked','approved','rejected') NOT NULL DEFAULT 'queued',
	`result` text,
	`requiresApproval` tinyint NOT NULL DEFAULT 0,
	`approvedBy` varchar(50),
	`approvedAt` timestamp,
	`errorMessage` text,
	`retryCount` int NOT NULL DEFAULT 0,
	`scheduledFor` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`durationMs` int,
	`costUsd` decimal(10,6) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agentActions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `agentMessages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fromAgent` varchar(50) NOT NULL,
	`toAgent` varchar(50) NOT NULL,
	`type` enum('directive','report','approval_request','approved','rejected','alert','info') NOT NULL,
	`priority` enum('p1','p2','p3','p4','p5') NOT NULL DEFAULT 'p3',
	`subject` varchar(500) NOT NULL,
	`body` text NOT NULL,
	`metadata` text,
	`status` enum('pending','read','acted_on','expired') NOT NULL DEFAULT 'pending',
	`parentMessageId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`readAt` timestamp,
	`actedAt` timestamp,
	CONSTRAINT `agentMessages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `agentRunLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentSlug` varchar(50) NOT NULL,
	`triggerType` enum('cron','manual','directive','event') NOT NULL DEFAULT 'cron',
	`triggeredBy` varchar(100),
	`status` enum('running','completed','failed','timeout') NOT NULL DEFAULT 'running',
	`summary` text,
	`actionsCreated` int DEFAULT 0,
	`messagesCreated` int DEFAULT 0,
	`model` varchar(200),
	`tokensIn` int DEFAULT 0,
	`tokensOut` int DEFAULT 0,
	`costUsd` decimal(10,6) DEFAULT '0',
	`llmCalls` int DEFAULT 0,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`durationMs` int,
	`errorMessage` text,
	`errorStack` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agentRunLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(50) NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`role` text NOT NULL,
	`status` enum('active','paused','error','idle') NOT NULL DEFAULT 'idle',
	`lastRunAt` timestamp,
	`lastRunDurationMs` int,
	`lastRunSummary` text,
	`totalRuns` int NOT NULL DEFAULT 0,
	`totalCostUsd` decimal(10,4) NOT NULL DEFAULT '0',
	`config` text,
	`cronExpression` varchar(100),
	`isEnabled` tinyint NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `agents_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `attorneyProspects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firmName` varchar(300) NOT NULL,
	`website` varchar(500),
	`phone` varchar(50),
	`email` varchar(320),
	`contactPerson` varchar(200),
	`city` varchar(100),
	`state` varchar(50),
	`statesCovered` text,
	`practiceAreas` text,
	`yearsInPractice` int,
	`foundedYear` int,
	`firmSize` varchar(50),
	`feeStructure` enum('contingency','hourly','flat_fee','hybrid','unknown') NOT NULL DEFAULT 'unknown',
	`contingencyPercent` varchar(20),
	`typicalCaseValue` varchar(100),
	`casesHandled` int,
	`successRate` varchar(20),
	`totalRecovered` varchar(100),
	`notableResults` text,
	`avgSettlement` varchar(100),
	`advertisingChannels` text,
	`seoKeywords` text,
	`estimatedAdSpend` varchar(50),
	`competitorOf` text,
	`overallScore` int NOT NULL DEFAULT 0,
	`scoreBreakdown` text,
	`outreachStatus` enum('not_contacted','researching','ready_to_pitch','pitched','in_conversation','signed','rejected','not_interested') NOT NULL DEFAULT 'not_contacted',
	`outreachNotes` text,
	`lastContactedAt` timestamp,
	`pitchAngle` text,
	`discoveredBy` varchar(50) DEFAULT 'money_maker',
	`discoveredVia` varchar(200),
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attorneyProspects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contentPipeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`slug` varchar(300),
	`contentType` enum('blog_article','city_page','company_page','landing_page','medium_article','press_release','social_post') NOT NULL DEFAULT 'blog_article',
	`targetKeyword` varchar(255),
	`secondaryKeywords` text,
	`searchVolume` int,
	`keywordDifficulty` int,
	`searchIntent` varchar(100),
	`outline` text,
	`draft` text,
	`finalContent` text,
	`wordCount` int,
	`stage` enum('idea','researching','outlined','drafting','draft_complete','in_review','revision_needed','approved','published','rejected') NOT NULL DEFAULT 'idea',
	`requestedBy` varchar(50),
	`assignedTo` varchar(50),
	`reviewedBy` varchar(50),
	`approvedBy` varchar(50),
	`editorFeedback` text,
	`managerFeedback` text,
	`revisionCount` int NOT NULL DEFAULT 0,
	`seoScore` int,
	`readabilityScore` int,
	`eatScore` int,
	`duplicateRisk` int,
	`revenueJustification` text,
	`estimatedMonthlyTraffic` int,
	`estimatedLeadsPerMonth` int,
	`publishedUrl` varchar(500),
	`publishedAt` timestamp,
	`blogPostId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contentPipeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenueTracker` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` enum('lead_sale','listing_fee','pay_per_click','pay_per_call','exclusive_territory','consultation','other') NOT NULL,
	`description` varchar(500),
	`amount` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`status` enum('pending','invoiced','paid','overdue','cancelled') NOT NULL DEFAULT 'pending',
	`firmId` int,
	`leadId` int,
	`firmName` varchar(200),
	`invoicedAt` timestamp,
	`paidAt` timestamp,
	`dueDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenueTracker_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seoChangeLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`changeType` enum('content_added','content_updated','content_removed','image_added','image_updated','image_removed','meta_updated','schema_updated','link_added','link_removed','technical_fix','page_speed','redirect_added','backlink_acquired','backlink_lost','design_change','other') NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text NOT NULL,
	`pagesAffected` text,
	`pageCount` int DEFAULT 1,
	`beforeSnapshot` text,
	`afterSnapshot` text,
	`impactMeasured` tinyint NOT NULL DEFAULT 0,
	`impactScore` int,
	`impactSummary` text,
	`impressionsDelta` int,
	`clicksDelta` int,
	`positionDelta` varchar(20),
	`measurementDate` timestamp,
	`madeBy` varchar(100),
	`relatedActionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seoChangeLog_id` PRIMARY KEY(`id`)
);
