CREATE TABLE `revenueIntelPredictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pageSlug` varchar(500) NOT NULL,
	`pageTitle` varchar(500),
	`actionType` varchar(100) NOT NULL,
	`actionDetail` text NOT NULL,
	`currentClicks` int DEFAULT 0,
	`currentPosition` varchar(10),
	`currentImpressions` int DEFAULT 0,
	`currentLeadsPerMonth` decimal(6,2) DEFAULT '0',
	`predictedClicksGain` int DEFAULT 0,
	`predictedLeadsGain` decimal(6,2) DEFAULT '0',
	`predictedRevenueGain` decimal(10,2) DEFAULT '0',
	`confidenceScore` int DEFAULT 0,
	`reasoning` text,
	`status` enum('queued','executing','done','skipped','failed') NOT NULL DEFAULT 'queued',
	`executedAt` timestamp,
	`executionNotes` text,
	`actualClicksGain` int,
	`actualLeadsGain` decimal(6,2),
	`actualRevenueGain` decimal(10,2),
	`outcomeRecordedAt` timestamp,
	`runId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenueIntelPredictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenueIntelRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runAt` timestamp NOT NULL DEFAULT (now()),
	`postsAnalyzed` int DEFAULT 0,
	`actionsGenerated` int DEFAULT 0,
	`actionsExecuted` int DEFAULT 0,
	`totalPredictedRevenueImpact` decimal(12,2) DEFAULT '0',
	`topAction` varchar(500),
	`topActionRevenue` decimal(10,2) DEFAULT '0',
	`summary` text,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`errorMessage` text,
	`durationMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `revenueIntelRuns_id` PRIMARY KEY(`id`)
);
