import express, { type Express } from "express";
import fs from "fs";
import { type Server } from "http";
import { nanoid } from "nanoid";
import path from "path";
import { createServer as createViteServer } from "vite";
import viteConfig from "../../vite.config";
import { buildMetaMap, injectMeta } from "../seo-meta";

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    server: serverOptions,
    appType: "custom",
  });

  app.use(vite.middlewares);
  app.use("*", async (req, res, next) => {
    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "../..",
        "client",
        "index.html"
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

/**
 * Resolve the dist/public directory robustly across different deployment environments.
 *
 * esbuild bundles all source files into a single dist/index.js. When a non-entry-point
 * module (like vite.ts) uses import.meta.dirname, esbuild resolves it to the SOURCE
 * file's directory at compile time, not the bundle output directory. This means
 * import.meta.dirname in vite.ts resolves to "server/_core/" (source), not "dist/" (output).
 *
 * To avoid this, we use process.cwd() + "dist/public" as the primary strategy in
 * production, which always resolves correctly regardless of the source file location.
 */
function resolveDistPath(): string {
  if (process.env.NODE_ENV === "development") {
    return path.resolve(import.meta.dirname, "../..", "dist", "public");
  }

  // In production: use process.cwd()/dist/public as the primary strategy
  const cwdBased = path.resolve(process.cwd(), "dist", "public");
  if (fs.existsSync(cwdBased)) {
    console.log(`[serveStatic] distPath (cwd-based): ${cwdBased}`);
    return cwdBased;
  }

  // Fallback: try import.meta.dirname-based path
  const dirnameBased = path.resolve(import.meta.dirname, "public");
  if (fs.existsSync(dirnameBased)) {
    console.log(`[serveStatic] distPath (dirname-based): ${dirnameBased}`);
    return dirnameBased;
  }

  console.error(`[serveStatic] Could not find dist/public. Tried:\n  ${cwdBased}\n  ${dirnameBased}`);
  return cwdBased;
}

export function serveStatic(app: Express) {
  const distPath = resolveDistPath();

  // Serve static assets (JS, CSS, images, etc.) — but NOT HTML directory indexes.
  // We handle HTML serving ourselves in the catch-all below so we can inject correct meta tags.
  // Setting index:false prevents express.static from serving index.html for directory requests,
  // which would bypass our pre-rendered file serving logic.
  app.use(express.static(distPath, { index: false }));

  // Pre-build the meta map at startup so first request is fast
  buildMetaMap();

  // Serve pre-rendered HTML for all page routes.
  // Pre-rendered files are generated by scripts/prerender.mjs at build time for all 371 URLs.
  // Each URL gets its own index.html with correct title, description, and canonical tags baked in.
  const indexPath = path.resolve(distPath, "index.html");
  app.use("*", (req, res) => {
    try {
      // IMPORTANT: When using app.use("*"), Express sets req.path = "/" always.
      // We must use req.originalUrl to get the actual request path.
      // Normalize: strip leading/trailing slashes and query string.
      // "/cancel-sunrun-solar-contract" → "cancel-sunrun-solar-contract"
      // "/cancel-sunrun-solar-contract/" → "cancel-sunrun-solar-contract"
      // "/cancel-solar-contract/dallas-tx" → "cancel-solar-contract/dallas-tx"
      const rawPath = req.originalUrl.split("?")[0]; // strip query string
      const urlPath = rawPath.replace(/^\/+|\/+$/g, ""); // strip leading/trailing slashes

      if (urlPath) {
        const prerenderedPath = path.resolve(distPath, urlPath, "index.html");
        if (fs.existsSync(prerenderedPath)) {
          res
            .set("Content-Type", "text/html")
            .set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
            .set("Surrogate-Control", "no-store")
            .set("CDN-Cache-Control", "no-store")
            .send(fs.readFileSync(prerenderedPath, "utf-8"));
          return;
        }
      }

      // Fallback: serve root index.html with dynamic meta injection
      const html = fs.readFileSync(indexPath, "utf-8");
      const injected = injectMeta(html, rawPath);
      res
        .set("Content-Type", "text/html")
        .set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
        .set("Surrogate-Control", "no-store")
        .set("CDN-Cache-Control", "no-store")
        .send(injected);
    } catch {
      res.sendFile(indexPath);
    }
  });
}
