import express, { type Express } from "express";
import fs from "fs";
import { type Server } from "http";
import { nanoid } from "nanoid";
import path from "path";
import { createServer as createViteServer } from "vite";
import viteConfig from "../../vite.config";
import { buildMetaMap, injectMeta } from "../seo-meta";

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    server: serverOptions,
    appType: "custom",
  });

  app.use(vite.middlewares);
  app.use("*", async (req, res, next) => {
    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "../..",
        "client",
        "index.html"
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

export function serveStatic(app: Express) {
  // Try import.meta.dirname first (esbuild sets this to the dir of dist/index.js)
  // Fall back to process.cwd()/dist/public if that doesn't exist
  let distPath =
    process.env.NODE_ENV === "development"
      ? path.resolve(import.meta.dirname, "../..", "dist", "public")
      : path.resolve(import.meta.dirname, "public");

  // Fallback: if import.meta.dirname-based path doesn't exist, try process.cwd()
  if (!fs.existsSync(distPath)) {
    const cwdPath = path.resolve(process.cwd(), "dist", "public");
    console.log(`[serveStatic] Primary distPath not found: ${distPath}`);
    console.log(`[serveStatic] Trying fallback: ${cwdPath}`);
    if (fs.existsSync(cwdPath)) {
      distPath = cwdPath;
      console.log(`[serveStatic] Using fallback distPath: ${distPath}`);
    } else {
      console.error(`[serveStatic] Could not find the build directory. Tried:\n  ${distPath}\n  ${cwdPath}`);
      console.log(`[serveStatic] import.meta.dirname = ${import.meta.dirname}`);
      console.log(`[serveStatic] process.cwd() = ${process.cwd()}`);
    }
  } else {
    console.log(`[serveStatic] distPath OK: ${distPath}`);
  }

  app.use(express.static(distPath));

  // Pre-build the meta map at startup so first request is fast
  buildMetaMap();

  // Fall through to index.html — serve pre-rendered HTML if it exists, otherwise inject meta tags
  // Pre-rendered files are generated by scripts/prerender.mjs at build time for all 371 URLs
  // This is Cloudflare-proof: static files are served directly with correct meta tags baked in
  // See docs/lessons-learned/01-spa-soft-404-seo.md
  const indexPath = path.resolve(distPath, "index.html");
  app.use("*", (req, res) => {
    try {
      // Check if a pre-rendered HTML file exists for this path
      const urlPath = req.path === "/" ? "" : req.path;
      const prerenderedPath = path.resolve(distPath, urlPath.replace(/^\//, ""), "index.html");
      
      if (urlPath && fs.existsSync(prerenderedPath)) {
        // Serve the pre-rendered file with correct meta tags already baked in
        res
          .set("Content-Type", "text/html")
          .set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
          .set("Surrogate-Control", "no-store")
          .set("CDN-Cache-Control", "no-store")
          .send(fs.readFileSync(prerenderedPath, "utf-8"));
        return;
      }

      // Fallback: inject meta tags dynamically for unmapped pages
      const html = fs.readFileSync(indexPath, "utf-8");
      const injected = injectMeta(html, req.path);
      res
        .set("Content-Type", "text/html")
        .set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
        .set("Surrogate-Control", "no-store")
        .set("CDN-Cache-Control", "no-store")
        .send(injected);
    } catch {
      res.sendFile(indexPath);
    }
  });
}
