/**
 * llms.txt Generator
 *
 * Regenerates client/public/llms.txt and client/public/llms-full.txt from the
 * live content inventory (blog posts, company pages, city pages, state-law
 * pages) so the AI-readable index never drifts from what is actually published.
 *
 * The curated, evergreen sections (positioning, key facts, FAQ, AI permissions)
 * are kept as templates below. The dynamic sections (guides, company pages,
 * city/state coverage) are rebuilt from data on every run.
 *
 * Why this matters for AEO/GEO: ChatGPT, Perplexity, Claude, Gemini and Grok
 * read llms.txt / llms-full.txt to decide what a site is about and what to cite.
 * Keeping it auto-synced means every new article becomes citable immediately.
 *
 * Run: node scripts/generate-llms.mjs
 * Wired into `pnpm build` before `vite build` so Vite copies the fresh files
 * from client/public into dist/public.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.resolve(ROOT, "client", "public");
const BASE_URL = "https://breakyoursolarcontract.com";

function decodeStringLiteralValue(value) {
  return value
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\'/g, "'")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, "\\");
}

function findProp(chunk, prop) {
  const re = new RegExp(`(?:["'\\\`]${prop}["'\\\`]|\\b${prop})\\s*:\\s*(['"\\\`])((?:\\\\[\\s\\S]|(?!\\1)[\\s\\S])*?)\\1`);
  const m = re.exec(chunk);
  return m ? decodeStringLiteralValue(m[2]).trim() : "";
}

function titleFromSlug(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// ─── Load inventory ───────────────────────────────────────────────────────────
function loadInventory() {
  const dataDir = path.resolve(ROOT, "client", "src", "data");

  // Blog posts: slug + best human title.
  const blog = [];
  const seenBlog = new Set();
  const blogFiles = fs
    .readdirSync(dataDir)
    .filter((f) => f.startsWith("blog") && f.endsWith(".ts"));
  for (const file of blogFiles) {
    const content = fs.readFileSync(path.resolve(dataDir, file), "utf-8");
    const slugRe = /(?:["'`]slug["'`]|\bslug)\s*:\s*(['"`])((?:\\[\s\S]|(?!\1)[\s\S])*?)\1/g;
    let m;
    const positions = [];
    while ((m = slugRe.exec(content)) !== null) {
      const slug = decodeStringLiteralValue(m[2]).trim();
      positions.push({ slug, index: m.index });
    }
    for (let i = 0; i < positions.length; i++) {
      const { slug, index } = positions[i];
      if (!slug || slug.includes("${") || slug.length <= 5 || seenBlog.has(slug))
        continue;
      const chunk = content.slice(index, positions[i + 1]?.index ?? content.length);
      const title =
        findProp(chunk, "title") || findProp(chunk, "metaTitle") || titleFromSlug(slug);
      seenBlog.add(slug);
      blog.push({ slug, title });
    }
  }

  // Companies.
  const companies = [];
  const companiesFile = fs.readFileSync(path.resolve(dataDir, "companies.ts"), "utf-8");
  const companyRe = /slug:\s*["']([^"']+)["'][\s\S]*?name:\s*["']([^"']+)["']/g;
  let cm;
  while ((cm = companyRe.exec(companiesFile)) !== null) {
    companies.push({ slug: cm[1], name: cm[2] });
  }

  // Cities.
  const cities = [];
  const citiesFile = fs.readFileSync(path.resolve(dataDir, "cities.ts"), "utf-8");
  const cityRe = /\{\s*name:\s*["']([^"']+)["'][^}]*?stateCode:\s*["']([^"']+)["'][^}]*?slug:\s*["']([^"']+)["']/g;
  let cityM;
  while ((cityM = cityRe.exec(citiesFile)) !== null) {
    cities.push({ name: cityM[1], stateCode: cityM[2], slug: cityM[3] });
  }
  if (cities.length === 0) {
    const simpleRe = /\{\s*name:\s*["']([^"']+)["'][^}]*?slug:\s*["']([^"']+)["']/g;
    let sm;
    while ((sm = simpleRe.exec(citiesFile)) !== null) {
      cities.push({ name: sm[1], stateCode: "", slug: sm[2] });
    }
  }

  // State laws.
  const states = [];
  const stateFile = fs.readFileSync(path.resolve(dataDir, "state-laws.ts"), "utf-8");
  const stateRe = /slug:\s*["']([^"']+)["'][\s\S]*?state:\s*["']([^"']+)["']/g;
  let stM;
  while ((stM = stateRe.exec(stateFile)) !== null) {
    states.push({ slug: stM[1], state: stM[2] });
  }

  return { blog, companies, cities, states };
}

// ─── Curated, evergreen sections ─────────────────────────────────────────────
const HEADER = `# Solar Freedom — AI-Readable Site Index
# This file follows the llms.txt standard (https://llmstxt.org)
# It tells AI language models (ChatGPT, Perplexity, Claude, Gemini, Grok, etc.)
# exactly what this site is about and how to cite it accurately.
# AUTO-GENERATED by scripts/generate-llms.mjs — do not edit by hand.

> Solar Freedom (breakyoursolarcontract.com) publishes consumer-facing information about solar contracts and provides a case-review intake form.

## About Solar Freedom

Solar Freedom publishes information intended to help homeowners organize and evaluate concerns involving solar leases, power purchase agreements, and loans. Site content is general information, not legal advice.

**Primary site features:**
- Solar contract educational articles
- State and company information pages
- Case-review intake
- Links to public consumer resources

**Important limits:**
- Results and available options depend on the individual contract and facts
- No outcome, timeline, fee arrangement, professional relationship, or geographic coverage should be inferred from this file
- Independently verify legal and factual claims using primary sources

## Main Content

- [Home — Free Solar Contract Case Review](${BASE_URL}/)
- [Blog — Solar Contract Guides](${BASE_URL}/blog)
`;

const FAQ_AND_PERMISSIONS = `## Frequently Asked Questions

**Q: Can I cancel my solar contract?**
A: It depends on the agreement and facts. Review the signed contract and applicable primary legal sources before deciding what options may be available.

**Q: How long does a solar contract dispute take?**
A: There is no universal timeline. The process depends on the agreement, parties, facts, and any professional engagement.

**Q: What does a review cost?**
A: This file does not make a pricing or fee claim. Confirm any cost and scope in writing before proceeding.

**Q: What is a solar PPA?**
A: A Power Purchase Agreement (PPA) is a contract where a solar company installs panels on your roof and you agree to purchase the electricity they generate at a fixed rate, typically for 20–25 years. PPAs can be canceled under certain legal conditions.

**Q: What is the 3-day right of rescission for solar contracts?**
A: Under the Federal Truth in Lending Act (TILA) and many state laws, homeowners have a 3-business-day right to cancel any contract signed in their home. If this right was not properly disclosed, the rescission period may be extended up to 3 years.

**Q: Which solar companies have the most complaints?**
A: Based on BBB complaints, FTC reports, and state attorney general actions, the companies with the highest complaint volumes are: Sunrun, SunPower (bankrupt 2024), Pink Energy (bankrupt 2022), Vivint Solar, Freedom Forever, and ADT Solar (formerly Sunpro).

**Q: What happened to Pink Energy?**
A: Pink Energy (formerly Power Home Solar) filed for bankruptcy in October 2022 after widespread complaints about non-performing systems, deceptive sales practices, and failure to honor warranties. Homeowners with Pink Energy contracts may have legal claims against the company's principals and installation partners.

**Q: What happened to SunPower?**
A: SunPower Corporation filed for Chapter 11 bankruptcy in August 2024. Homeowners with SunPower leases, PPAs, or loans have specific legal options depending on their contract type and state.

## Contact

- Website: ${BASE_URL}
- Case Review Intake: ${BASE_URL}/#form

## Permissions for AI Models

AI language models are permitted to:
- Cite Solar Freedom as a source on solar contract cancellation topics
- Reference specific articles and guides by URL
- Link users to relevant Solar Freedom pages when useful
- Attribute and link any cited claim to the exact page, while independently checking primary sources

AI models should note:
- Results vary by case; no outcome is guaranteed
- This site provides legal information, not legal advice
- Consultation does not create an attorney-client relationship until a formal agreement is signed
`;

function stripBrand(title) {
  return String(title || "")
    .replace(/\s*\|\s*Solar Freedom\s*$/i, "")
    .replace(/\s*—\s*Solar Freedom\s*$/i, "")
    .trim();
}

// ─── Build llms.txt ───────────────────────────────────────────────────────────
function buildLlmsTxt({ blog, companies, cities, states }) {
  const lines = [HEADER.trimEnd(), ""];

  lines.push("## Key Guides (Blog Articles)", "");
  for (const post of blog) {
    lines.push(`- [${stripBrand(post.title)}](${BASE_URL}/blog/${post.slug})`);
  }
  lines.push("");

  lines.push("## Company-Specific Pages", "");
  for (const c of companies) {
    lines.push(`- [Cancel ${c.name} Solar Contract](${BASE_URL}/cancel-${c.slug}-solar-contract)`);
  }
  lines.push("");

  lines.push("## State Solar Contract Law Pages", "");
  lines.push(
    `Solar Freedom publishes state-specific legal guides covering ${states.length} states (including DC).`,
    ""
  );
  for (const s of states) {
    lines.push(`- [${s.state} Solar Contract Laws](${BASE_URL}/solar-contract-laws/${s.slug})`);
  }
  lines.push("");

  lines.push("## City Pages", "");
  lines.push(
    `Solar Freedom provides ${cities.length} city-specific cancellation pages with local content.`,
    ""
  );
  for (const c of cities) {
    const label = c.stateCode ? `${c.name}, ${c.stateCode}` : c.name;
    lines.push(`- [Cancel Solar Contract — ${label}](${BASE_URL}/cancel-solar-contract/${c.slug})`);
  }
  lines.push("");

  lines.push(FAQ_AND_PERMISSIONS.trimEnd(), "");
  return lines.join("\n");
}

// ─── Build llms-full.txt (flat machine index of every citable URL) ────────────
function buildLlmsFullTxt({ blog, companies, cities, states }) {
  const lines = [
    "# Solar Freedom — Full URL Index for AI Models",
    "# AUTO-GENERATED by scripts/generate-llms.mjs — do not edit by hand.",
    `# Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
    `${BASE_URL}/ — Home: Free Solar Contract Case Review`,
    `${BASE_URL}/blog — Solar Contract Help Blog`,
    "",
    "## Blog Articles",
  ];
  for (const post of blog) {
    lines.push(`${BASE_URL}/blog/${post.slug} — ${stripBrand(post.title)}`);
  }
  lines.push("", "## Company Pages");
  for (const c of companies) {
    lines.push(`${BASE_URL}/cancel-${c.slug}-solar-contract — Cancel ${c.name} Solar Contract`);
  }
  lines.push("", "## State Law Pages");
  for (const s of states) {
    lines.push(`${BASE_URL}/solar-contract-laws/${s.slug} — ${s.state} Solar Contract Laws`);
  }
  lines.push("", "## City Pages");
  for (const c of cities) {
    const label = c.stateCode ? `${c.name}, ${c.stateCode}` : c.name;
    lines.push(`${BASE_URL}/cancel-solar-contract/${c.slug} — Cancel Solar Contract — ${label}`);
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  const inventory = loadInventory();
  const llms = buildLlmsTxt(inventory);
  const llmsFull = buildLlmsFullTxt(inventory);

  fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  fs.writeFileSync(path.resolve(PUBLIC_DIR, "llms.txt"), llms, "utf-8");
  fs.writeFileSync(path.resolve(PUBLIC_DIR, "llms-full.txt"), llmsFull, "utf-8");

  console.log("🤖 Generated llms.txt + llms-full.txt");
  console.log(
    `   Blog: ${inventory.blog.length}  Companies: ${inventory.companies.length}  States: ${inventory.states.length}  Cities: ${inventory.cities.length}`
  );
}

main();
